# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/sun/PycharmProjects/RISC-V_Debugger/GUI/ui_BreakPointDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(306, 428)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMaximumSize(QtCore.QSize(9999, 600))
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 350, 161, 71))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(21, 47, 271, 308))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.textBrowser_00 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_00.setEnabled(True)
        self.textBrowser_00.setMaximumSize(QtCore.QSize(180, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.textBrowser_00.setFont(font)
        self.textBrowser_00.setObjectName("textBrowser_00")
        self.verticalLayout.addWidget(self.textBrowser_00)
        self.textBrowser_01 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_01.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_01.setObjectName("textBrowser_01")
        self.verticalLayout.addWidget(self.textBrowser_01)
        self.textBrowser_02 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_02.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_02.setObjectName("textBrowser_02")
        self.verticalLayout.addWidget(self.textBrowser_02)
        self.textBrowser_03 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_03.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_03.setObjectName("textBrowser_03")
        self.verticalLayout.addWidget(self.textBrowser_03)
        self.textBrowser_04 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_04.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_04.setObjectName("textBrowser_04")
        self.verticalLayout.addWidget(self.textBrowser_04)
        self.textBrowser_05 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_05.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_05.setObjectName("textBrowser_05")
        self.verticalLayout.addWidget(self.textBrowser_05)
        self.textBrowser_06 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_06.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_06.setObjectName("textBrowser_06")
        self.verticalLayout.addWidget(self.textBrowser_06)
        self.textBrowser_07 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_07.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_07.setObjectName("textBrowser_07")
        self.verticalLayout.addWidget(self.textBrowser_07)
        self.textBrowser_08 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_08.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_08.setObjectName("textBrowser_08")
        self.verticalLayout.addWidget(self.textBrowser_08)
        self.textBrowser_09 = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser_09.setMaximumSize(QtCore.QSize(180, 25))
        self.textBrowser_09.setObjectName("textBrowser_09")
        self.verticalLayout.addWidget(self.textBrowser_09)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_00 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_00.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_00.setClearButtonEnabled(False)
        self.lineEdit_00.setObjectName("lineEdit_00")
        self.verticalLayout_4.addWidget(self.lineEdit_00)
        self.lineEdit_01 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_01.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_01.setClearButtonEnabled(False)
        self.lineEdit_01.setObjectName("lineEdit_01")
        self.verticalLayout_4.addWidget(self.lineEdit_01)
        self.lineEdit_02 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_02.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_02.setClearButtonEnabled(False)
        self.lineEdit_02.setObjectName("lineEdit_02")
        self.verticalLayout_4.addWidget(self.lineEdit_02)
        self.lineEdit_03 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_03.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_03.setClearButtonEnabled(False)
        self.lineEdit_03.setObjectName("lineEdit_03")
        self.verticalLayout_4.addWidget(self.lineEdit_03)
        self.lineEdit_04 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_04.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_04.setClearButtonEnabled(False)
        self.lineEdit_04.setObjectName("lineEdit_04")
        self.verticalLayout_4.addWidget(self.lineEdit_04)
        self.lineEdit_05 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_05.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_05.setClearButtonEnabled(False)
        self.lineEdit_05.setObjectName("lineEdit_05")
        self.verticalLayout_4.addWidget(self.lineEdit_05)
        self.lineEdit_06 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_06.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_06.setClearButtonEnabled(False)
        self.lineEdit_06.setObjectName("lineEdit_06")
        self.verticalLayout_4.addWidget(self.lineEdit_06)
        self.lineEdit_07 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_07.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_07.setClearButtonEnabled(False)
        self.lineEdit_07.setObjectName("lineEdit_07")
        self.verticalLayout_4.addWidget(self.lineEdit_07, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_08 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_08.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_08.setClearButtonEnabled(False)
        self.lineEdit_08.setObjectName("lineEdit_08")
        self.verticalLayout_4.addWidget(self.lineEdit_08)
        self.lineEdit_09 = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_09.setMaximumSize(QtCore.QSize(100, 25))
        self.lineEdit_09.setClearButtonEnabled(False)
        self.lineEdit_09.setObjectName("lineEdit_09")
        self.verticalLayout_4.addWidget(self.lineEdit_09)
        self.horizontalLayout.addLayout(self.verticalLayout_4)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Breakpoint Management"))
        self.textBrowser_00.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\';\">BreakPoint 0</span></p></body></html>"))
        self.textBrowser_01.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 1</p></body></html>"))
        self.textBrowser_02.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 2</p></body></html>"))
        self.textBrowser_03.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 3</p></body></html>"))
        self.textBrowser_04.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 4</p></body></html>"))
        self.textBrowser_05.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 5</p></body></html>"))
        self.textBrowser_06.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 6</p></body></html>"))
        self.textBrowser_07.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 7</p></body></html>"))
        self.textBrowser_08.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 8</p></body></html>"))
        self.textBrowser_09.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">BreakPoint 9</p></body></html>"))
        self.lineEdit_00.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_01.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_02.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_03.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_04.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_05.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_06.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_07.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_08.setInputMask(_translate("Dialog", "HHHH"))
        self.lineEdit_09.setInputMask(_translate("Dialog", "HHHH"))
